services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - achim-network

networks:
  achim-network:
    external: true
