services:

  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - achim-network

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - achim-network

networks:
  achim-network:
    driver: bridge

volumes:
  pgdata:
